services:

    #services:

    Borsaco\TelegramBotApiBundle\Service\Bot:
        arguments: ['@service_container']

    # commands:

    Borsaco\TelegramBotApiBundle\Command\WebhookSetCommand:
        arguments: ['@Borsaco\TelegramBotApiBundle\Service\Bot']
        tags:
            - { name: console.command }

    Borsaco\TelegramBotApiBundle\Command\WebhookDeleteCommand:
        arguments: ['@Borsaco\TelegramBotApiBundle\Service\Bot']
        tags:
            - { name: console.command }

    Borsaco\TelegramBotApiBundle\Command\WebhookInfoCommand:
        arguments: ['@Borsaco\TelegramBotApiBundle\Service\Bot']
        tags:
            - { name: console.command }

